name: rbazaar
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1
  # State Management and DI
  get: ^3.11.1

  # Storage and Http Client
  dio: ^3.0.10
  sqflite: ^1.3.1+1
  path_provider: ^1.6.5

  # Firbase
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.0
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.2.0
  # Pattern and Arch
  rxdart: ^0.24.1
  # Other
  connectivity: ^0.4.9+2
  device_info: ^0.4.2+7
  sms_autofill: ^1.2.5
  easy_localization: ^2.3.3
  get_storage: ^1.3.1
  location: ^3.0.2
  url_launcher: ^5.7.2
  flutter_staggered_grid_view: ^0.3.2
  titled_navigation_bar: ^4.1.0
  percent_indicator: ^2.1.7+4
  timeago: ^2.0.28
  flutter_svg: ^0.18.0
  # toast
  fluttertoast: ^7.1.1
  # HTML
  html: ^0.14.0+4
  flutter_html: ^1.0.2
  # PIN CODE FILL
  pin_input_text_field: ^3.1.1
  # LOADER
  flutter_spinkit: ^4.1.2+1
  # PULL TO REFRESH
  pull_to_refresh: ^1.6.2
  bot_toast: ^3.0.4
  # google
  flutter_google_places: ^0.2.6
  geocoder: ^0.2.1
  shared_preferences: ^0.5.12+4
  flutter_cached_pdfview: ^0.3.4
#  pdf_flutter: ^1.1.3
  image_cropper: ^1.3.0
  image_picker: ^0.6.7+7
  provider: ^4.0.4
  permission_handler: ^4.0.0
  paytm: ^2.0.0
  paytm_allinonesdk: ^1.0.0
  flutter_countdown_timer: ^3.0.1
  webview_flutter: ^0.3.24
  package_info: ^0.4.3+2
  firebase_remote_config: ^0.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  # Launching icon
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Karla
      fonts:
        - asset: font/Karla-Bold.ttf
        - asset: font/Karla-BoldItalic.ttf
        - asset: font/Karla-Italic.ttf
        - asset: font/Karla-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
